### ISSUE TITLE
it's rendering a white background help !?!

### ISSUE THREAD

**Issue by nathanielfernandes** [fabyanMikhael/rust-pixels#1]
I compiled and ran the code however it is not doing what it says. I am only see white help why white ???!??!

**Comment by fabyanMikhael** [comment]
nah

**Comment by nathanielfernandes** [comment]
aye bruh thats not how this works.
get beaned
![beans](https://cdn.discordapp.com/attachments/869367514008793128/879270360397275156/maxresdefault.png)
